### ISSUE TITLE
`Missing required parameter: "httpUsername"` after upgrading to 

### ISSUE THREAD

**Issue by felipecrs** [jenkinsci/sonar-gerrit-plugin#106]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins: 2.319.1
OS: Linux - 4.4.0-141-generic
---
Parameterized-Remote-Trigger:3.1.5.1
ace-editor:1.1
allure-jenkins-plugin:2.29.0
analysis-model-api:10.8.1
ansicolor:1.0.1
ant:1.13
antisamy-markup-formatter:2.6
apache-httpcomponents-client-4-api:4.5.13-1.0
artifactory:3.15.1
async-http-client:1.9.40.0
authentication-tokens:1.4
authorize-project:1.4.0
aws-credentials:1.33
aws-java-sdk-ec2:1.12.131-302.vbef9650c6521
aws-java-sdk-minimal:1.12.131-302.vbef9650c6521
basic-branch-build-strategies:1.3.2
blueocean:1.25.2
blueocean-autofavorite:1.2.4
blueocean-bitbucket-pipeline:1.25.2
blueocean-commons:1.25.2
blueocean-config:1.25.2
blueocean-core-js:1.25.2
blueocean-dashboard:1.25.2
blueocean-display-url:2.4.1
blueocean-events:1.25.2
blueocean-git-pipeline:1.25.2
blueocean-github-pipeline:1.25.2
blueocean-i18n:1.25.2
blueocean-jwt:1.25.2
blueocean-personalization:1.25.2
blueocean-pipeline-api-impl:1.25.2
blueocean-pipeline-editor:1.25.2
blueocean-pipeline-scm-api:1.25.2
blueocean-rest:1.25.2
blueocean-rest-impl:1.25.2
blueocean-web:1.25.2
bootstrap4-api:4.6.0-3
bootstrap5-api:5.1.3-4
bouncycastle-api:2.25
branch-api:2.7.0
build-environment:1.7
build-name-setter:2.2.0
caffeine-api:2.9.2-29.v717aac953ff3
checks-api:1.7.2
cloudbees-bitbucket-branch-source:737.vdf9dc06105be
cloudbees-folder:6.17
cobertura:1.17
code-coverage-api:2.0.4
command-launcher:1.6
conditional-buildstep:1.4.1
config-file-provider:3.8.2
copyartifact:1.46.2
credentials:1074.v60e6c29b_b_44b_
credentials-binding:1.27
cucumber-living-documentation:3.2
cucumber-perf:2.0.9
cucumber-reports:5.6.1
cucumber-trends-report:1.3
dark-theme:155.v497c78bbdbb3
dashboard-view:2.18
data-tables-api:1.11.3-6
display-url-api:2.3.5
docker-commons:1.17
docker-java-api:3.1.5.2
docker-plugin:1.2.6
docker-workflow:1.26
dockerhub-notification:2.5.3
dtkit-api:3.0.0
durable-task:493.v195aefbb0ff2
echarts-api:5.2.2-2
email-ext:2.86
embeddable-build-status:2.0.3
envinject:2.4.0
envinject-api:1.8
extended-choice-parameter:0.82
extended-read-permission:3.2
extensible-choice-parameter:1.8.0
external-monitor-job:1.7
favorite:2.3.3
file-parameters:146.v7d35212829d0
font-awesome-api:5.15.4-5
forensics-api:1.7.0
gerrit-code-review:0.4.7
gerrit-trigger:2.35.2
git:4.10.1
git-client:3.11.0
git-parameter:0.9.14
git-server:1.10
github:1.34.1
github-api:1.301-378.v9807bd746da5
github-autostatus:3.6.2
github-branch-source:2.11.4
gradle:1.38
handlebars:3.0.8
handy-uri-templates-2-api:2.1.8-1.0
htmlpublisher:1.28
ivy:2.1
jackson2-api:2.13.1-246.va8a9f3eaf46a
jacoco:3.3.1
javadoc:1.6
jaxb:2.3.0.1
jdk-tool:1.5
jenkins-design-language:1.25.2
jira:3.6
jjwt-api:0.11.2-9.c8b45b8bb173
jobConfigHistory:2.31-rc1098.b666422863b2
jquery:1.12.4-1
jquery-detached:1.2.1
jquery3-api:3.6.0-2
jsch:0.1.55.2
junit:1.53
kubernetes:1.31.2
kubernetes-client-api:5.11.2-182.v0f1cf4c5904e
kubernetes-credentials:0.9.0
last-changes:2.7.11
ldap:2.7
lockable-resources:2.13
mailer:391.ve4a_38c1b_cf4b_
mapdb-api:1.0.9.0
matrix-auth:2.6.11
matrix-project:1.19
maven-plugin:3.16
metrics:4.0.2.8
momentjs:1.1.1
monitoring:1.90.0
multibranch-build-strategy-extension:1.0.10
okhttp-api:4.9.3-105.vb96869f8ac3a
pam-auth:1.6.1
parameterized-trigger:2.43
pipeline-build-step:2.15
pipeline-graph-analysis:188.v3a01e7973f2c
pipeline-input-step:427.va6441fa17010
pipeline-milestone-step:1.3.2
pipeline-model-api:1.9.3
pipeline-model-definition:1.9.3
pipeline-model-extensions:1.9.3
pipeline-rest-api:2.20
pipeline-stage-step:291.vf0a8a7aeeb50
pipeline-stage-tags-metadata:1.9.3
pipeline-stage-view:2.20
pipeline-utility-steps:2.11.0
plain-credentials:1.7
plugin-util-api:2.12.0
popper-api:1.16.1-2
popper2-api:2.11.0-1
pubsub-light:1.16
purge-build-queue-plugin:1.0
rebuild:1.32
resource-disposer:0.17
role-strategy:3.2.0
run-condition:1.5
saferestart:0.3
scm-api:595.vd5a_df5eb_0e39
scm-filter-branch-pr:0.5.1
script-security:1131.v8b_b_5eda_c328e
snakeyaml-api:1.29.1
sonar:2.14
sonar-gerrit:351.vb_8d85df69260
sse-gateway:1.24
ssh-credentials:1.19
ssh-slaves:1.33.0
sshd:3.1.0
strict-crumb-issuer:2.1.0
structs:308.v852b473a2b8c
subversion:2.15.1
theme-manager:0.6
timestamper:1.16
token-macro:267.vcdaea6462991
trilead-api:1.0.13
uno-choice:2.5.7
variant:1.4
windows-slaves:1.8
workflow-aggregator:2.6
workflow-api:1108.v57edf648f5d4
workflow-basic-steps:2.24
workflow-cps:2648.va9433432b33c
workflow-cps-global-lib:552.vd9cc05b8a2e1
workflow-durable-task-step:1112.vda00e6febcc1
workflow-job:1145.v7f2433caa07f
workflow-multibranch:704.v8f039a_e2e8cf
workflow-scm-step:2.13
workflow-step-api:622.vb_8e7c15b_c95a_
workflow-support:804.vba10a18a1476
ws-cleanup:0.40
xunit:3.0.5
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Controller: jenkins/jenkins:lts-jdk11

Agents: Ubuntu 20.04

### Reproduction steps

1. To have a working setup with v351.vb_8d85df69260
2. Upgrade to 353.v20e9cff705d1 :P

Sorry, if you need more details please let me know.

### Expected Results

To work as it was working in v351.vb_8d85df69260, and because no breaking changes were advised.

### Actual Results

  ```text
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
 WorkflowScript: 58: Missing required parameter: "httpUsername" @ line 58, column 17.
                    sonarToGerrit (
                    ^
 
 WorkflowScript: 58: Missing required parameter: "httpPassword" @ line 58, column 17.
                    sonarToGerrit (
                    ^
 
 2 errors
 
 	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:310)
 	at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1085)
 	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:603)
 	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:581)
 	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:558)
 	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:298)
 	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:268)
 	at groovy.lang.GroovyShell.parseClass(GroovyShell.java:688)
 	at groovy.lang.GroovyShell.parse(GroovyShell.java:700)
 	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.doParse(CpsGroovyShell.java:142)
 	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.reparse(CpsGroovyShell.java:127)
 	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.parseScript(CpsFlowExecution.java:571)
 	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.start(CpsFlowExecution.java:523)
 	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:334)
 	at hudson.model.ResourceController.execute(ResourceController.java:99)
 	at hudson.model.Executor.run(Executor.java:432)
  ```

### Anything else?

Downgrading to v351.vb_8d85df69260 solves the issue for now. Upgrading to 361.v3f45367a_71da_ keeps the issue.

https://mirror.gruenehoelle.nl/jenkins/plugins/sonar-gerrit/351.vb_8d85df69260/sonar-gerrit.hpi

**Comment by reda-alaoui** [comment]
Can you provide groovy part where you call the plugin please?

**Comment by felipecrs** [comment]
Sure:

```groovy
sonarToGerrit (
    inspectionConfig: [
        serverURL: '<coalesced>',
        baseConfig: [
            projectPath: '',
            sonarReportPath: 'target/sonar/sonar-report.json',
            autoMatch: true
        ]
    ],
    reviewConfig: [
        issueFilterConfig: [
            severity: 'INFO',
            newIssuesOnly: true,
            changedLinesOnly: false
        ],
        noIssuesTitleTemplate: 'SonarQube violations have not been found.',
        someIssuesTitleTemplate: '<total_count> SonarQube violations have been found.',
        issueCommentTemplate: '<severity> SonarQube violation:\n\n\n<message>\n\n\nRead more: <rule_url>'
    ],
    scoreConfig: [
        issueFilterConfig: [
            severity: 'INFO',
            newIssuesOnly: true,
            changedLinesOnly: false
        ],
        category: 'Sonar-Verified',
        noIssuesScore: +1,
        issuesScore: -1
    ]
)
```

**Comment by reda-alaoui** [comment]
Are you using a scripted or declarative pipeline?

**Comment by felipecrs** [comment]
Declarative

**Comment by felipecrs** [comment]
Forgot to mention that it fails very early, during the Jenkinsfile syntax check (which means the pipeline does not get executed at all).

**Comment by reda-alaoui** [comment]
The most probable explanation is that declarative pipeline behaves differently from scripted pipeline regarding `@DataboundConstructor`. That would explain why https://github.com/jenkinsci/sonar-gerrit-plugin/blob/3f45367a71da0c3930a5aaefa9a6196b2e17c4e9/src/test/java/org/jenkinsci/plugins/sonargerrit/PreviewModeAnalysisTest.java#L206 passes .
Let's see if I can find a quick fix

**Comment by felipecrs** [comment]
> Let's see if I can find a quick fix

I already downgraded in my instance, so... if it's for me, don't worry. Take your time. And thanks for maintaining the plugin by the way, it helps a lot.

**Comment by felipecrs** [comment]
![1-1641845602650](https://user-images.githubusercontent.com/29582865/148832788-5fd44ad4-2d75-4d07-ae08-2f93211275a1.png)

This is how my server is configured btw.

**Comment by felipecrs** [comment]
I can confirm that 362.v43a_b_52a_b_23a_5 solves the issue. Thanks for the quick fix!
