### ISSUE TITLE
NullPointerException: GERRIT_NAME not found

### ISSUE THREAD

**Issue by reda-alaoui** [jenkinsci/sonar-gerrit-plugin#67]
<p>I use currently a multibranch pipeline and want to integrate the sonar finding in our gerrit process. As far as I know it is not recommended to use the plugin without the gerrit-trigger-plugin but it should work regarding the documentation. </p>
<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>In case when the plugin is runing outside of a job with Gerrit Trigger the next environmental variables should be set:

GERRIT_NAME - Gerrit server name
GERRIT_CHANGE_NUMBER - Change number
GERRIT_PATCHSET_NUMBER - Patchset number</pre>
</div></div>
<p>However, I tried to set the GERRIT_NAME as environment variable with the environment{} block and with the withEnv{} wrapper and always get a NPE.</p>
<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:187)
	at com.google.common.base.MoreObjects.firstNonNull(MoreObjects.java:52)
	at org.jenkinsci.plugins.sonargerrit.review.GerritConnectionInfo.retrieveServerName(GerritConnectionInfo.java:76)</pre>
</div></div>
<p> </p>
<i>[JENKINS-64333] created by incrediblelou</i>

**Comment by reda-alaoui** [comment]
This was caused by https://issues.jenkins.io/browse/JENKINS-29144 (discovered in https://github.com/jenkinsci/sonar-gerrit-plugin/pull/39#issue-1037600794).
Should be fixed in 3.0.0 .
